function plotStats(fig, obj)

bgStats1 = uibuttongroup(fig);
bgStats1.Position = [0.84, 0.41, 0.16, 0.37];
bgStats1.BackgroundColor = [0.9, 0.9, 0.9];
bgTitle = 'Summary';
if ~isnan(obj.outcomeStartTime)
    bgTitle = strcat(bgTitle, sprintf('\n%02.0f:%02.0f <> ', floor(mod(obj.outcomeStartTime, 1440)/60), mod(obj.outcomeStartTime, 60)));
    if ~isnan(obj.outcomeEndTime)
        bgTitle = strcat(bgTitle, sprintf('%02.0f:%02.0f', floor(mod(obj.outcomeEndTime, 1440)/60), mod(obj.outcomeEndTime, 60)));
    else
        bgTitle = strcat(bgTitle, 'End');
    end
elseif ~isnan(obj.outcomeEndTime)
    bgTitle = sprintf('\nUntill %02.0f:%02.0f', floor(mod(obj.outcomeEndTime, 1440)/60), mod(obj.outcomeEndTime, 60));
end
bgStats1.Tag = bgTitle;

[sensorPerc, sensorTime] = obj.getSensorTime(obj.intervalToIndices([0, 0]));

fields = { ...
    'Sensor Time',...
    {num2str(sensorTime/60, '%4.1f h');...
    num2str(sensorPerc, '%4.1f %%')}; ...
    'Total Treats',...
    {num2str(obj.getTreats(obj.intervalToIndices([0, 0])), '%4.1f g');...
    num2str(obj.getTreats(obj.intervalToIndices([0, 0]))/days(obj.durationOutcome), '%4.1f g/day')}; ...
    'Total Meals',...
    {num2str(obj.getCarbs(obj.intervalToIndices([0, 0])), '%4.1f g');...
    num2str(obj.getCarbs(obj.intervalToIndices([0, 0]))/days(obj.durationOutcome), '%4.1f g/day')}; ...
    'Total Bolus',...
    {num2str(obj.getTDBolus(obj.intervalToIndices([0, 0])), '%4.1f U');...
    num2str(obj.getTDBolus(obj.intervalToIndices([0, 0]))/days(obj.durationOutcome), '%4.1f U/day');...
    num2str(100*obj.getTDBolus(obj.intervalToIndices([0, 0]))/obj.getTDD(obj.intervalToIndices([0, 0])), '%4.1f %%')}; ...
    'Total Basal',...
    {num2str(obj.getTDBasal(obj.intervalToIndices([0, 0])), '%4.1f U');...
    num2str(obj.getTDBasal(obj.intervalToIndices([0, 0]))/days(obj.durationOutcome), '%4.1f U/day');...
    num2str(100*obj.getTDBasal(obj.intervalToIndices([0, 0]))/obj.getTDD(obj.intervalToIndices([0, 0])), '%4.1f %%')}; ...
    'Total Insulin',...
    {num2str(obj.getTDD(obj.intervalToIndices([0, 0])), '%4.1f U');...
    num2str(obj.getTDD(obj.intervalToIndices([0, 0]))/days(obj.durationOutcome), '%4.1f U/day')}; ...
    };

if nansum(obj.tdd) > 0
    fields(end+1, :) = {'Usual Total Insulin', {num2str(nanmean(obj.tdd), '%4.1f U/day')}};
end

MAPUtils.plotTable( ...
    bgStats1, ...
    fields, ...
    'TitleFont', 12, ...
    'YPad', 0.015, ...
    'YOffset', 0.01, ...
    'XOffset', 0.01, ...
    'XPad', 0.005, ...
    'XTitleLength', 0.3, ...
    'XTitleFont', 10, ...
    'TableFont', 10);

bgStats2 = uibuttongroup(fig);
bgStats2.Position = [0.84, 0.13, 0.16, 0.27];
bgStats2.BackgroundColor = [0.9, 0.9, 0.9];
bgTitle = 'Outcomes';
if ~isnan(obj.outcomeStartTime)
    bgTitle = strcat(bgTitle, sprintf('\n%02.0f:%02.0f <> ', floor(mod(obj.outcomeStartTime, 1440)/60), mod(obj.outcomeStartTime, 60)));
    if ~isnan(obj.outcomeEndTime)
        bgTitle = strcat(bgTitle, sprintf('%02.0f:%02.0f', floor(mod(obj.outcomeEndTime, 1440)/60), mod(obj.outcomeEndTime, 60)));
    else
        bgTitle = strcat(bgTitle, 'End');
    end
elseif ~isnan(obj.outcomeEndTime)
    bgTitle = sprintf('\nUntill %02.0f:%02.0f', floor(mod(obj.outcomeEndTime, 1440)/60), mod(obj.outcomeEndTime, 60));
end
bgStats2.Tag = bgTitle;

fields = { ...
    'Time > 10 (mmol/L)', ...
    {num2str(obj.getTimeIn(10+1e-5, inf, obj.intervalToIndices([0, 0])), '%4.1f %%'); ...
    num2str(obj.getTimeIn(10+1e-5, inf, obj.intervalToIndices(obj.dayInterval)), '%4.1f %%'); ...
    num2str(obj.getTimeIn(10+1e-5, inf, obj.intervalToIndices(obj.nightInterval)), '%4.1f %%')}; ...
    'Time < 3.9 (mmol/L)', ...
    {num2str(obj.getTimeIn(0, 3.9, obj.intervalToIndices([0, 0])), '%4.1f %%'); ...
    num2str(obj.getTimeIn(0, 3.9, obj.intervalToIndices(obj.dayInterval)), '%4.1f %%'); ...
    num2str(obj.getTimeIn(0, 3.9, obj.intervalToIndices(obj.nightInterval)), '%4.1f %%')}; ...
    'Time in Target', ...
    {num2str(obj.getTimeIn(3.9, 10+1e-5, obj.intervalToIndices([0, 0])), '%4.1f %%'); ...
    num2str(obj.getTimeIn(3.9, 10+1e-5, obj.intervalToIndices(obj.dayInterval)), '%4.1f %%'); ...
    num2str(obj.getTimeIn(3.9, 10+1e-5, obj.intervalToIndices(obj.nightInterval)), '%4.1f %%')}; ...
    'Title', ...
    {'Overall'; ...
    sprintf('%02.0f:00 <> %02.0f:00', obj.dayInterval(1)/60, obj.dayInterval(2)/60); ...
    sprintf('%02.0f:00 <> %02.0f:00', obj.nightInterval(1)/60, obj.nightInterval(2)/60)}; ...
    };

if nansum(obj.closedLoopActive) > 0
    fields = [{'Time in Closed-Loop', ...
        {num2str(obj.getTimeInCL(obj.intervalToIndices([0, 0])), '%4.1f %%'); ...
        num2str(obj.getTimeInCL(obj.intervalToIndices(obj.dayInterval)), '%4.1f %%'); ...
        num2str(obj.getTimeInCL(obj.intervalToIndices(obj.nightInterval)), '%4.1f %%')}}; ...
        fields];
end

MAPUtils.plotTable( ...
    bgStats2, ...
    fields, ...
    'TitleFont', 11, ...
    'YPad', 0.015, ...
    'YOffset', 0.01, ...
    'XOffset', 0.01, ...
    'XPad', 0.01, ...
    'XTitleLength', 0.3, ...
    'XTitleFont', 10, ...
    'TableFont', 10);
